version: '3'
services:
  mariadb:
    image: mariadb:10.2
    container_name: dockermariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: usermanagement
    ports:
    - '6033:3306'
    networks:
      - springboot
    restart: always

  admin-server:
    image: admin-server
    container_name: admin-server
    ports:
    - '8889:8889'
    restart: always
    networks:
    - springboot
    
  application-properties:
    image: application-properties
    container_name: application-properties
    ports:
    - '8888:8888'
    restart: always
    depends_on:
    - admin-server
    networks:
    - springboot
    
  authentication:
    image: authentication
    container_name: authentication
    build:
      context: ./authentication
      dockerfile: Dockerfile
    ports:
    - '9000:9000'
    restart: always
    depends_on:
    - mariadb
    - application-properties
    networks:
    - springboot
    
  client-app:
    image: clientapp
    container_name: clientapp
    build:
      context: ./client-app
      dockerfile: Dockerfile
    restart: always
    depends_on:
    - authentication
    networks:
    - springboot
    
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
    - '8000:80'
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
    - application-properties
    - authentication
    networks:
    - springboot
    
networks:
  springboot: